### ISSUE TITLE
sign-compare compiler warning

### ISSUE THREAD

**Issue by cgzones** [westes/flex#61]
https://github.com/westes/flex/blob/master/src/flex.skl#L1781 is raising sign-compare warnings with flex 2.6.0 on debian sid for me:

gcc-5 / gcc-6:
```
<stdout>: In function ‘yy_get_next_buffer’:
<stdout>:1113:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

clang-3.8:
```
<stdout>:1113:44: warning: comparison of integers of different signs: 'int' and 'yy_size_t' (aka 'unsigned long') [-Wsign-compare]
        if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
```

**Comment by westes** [comment]
This should be resolved in current master. Your report mentions 2.6.0, so please check this against the current tip of master.

**Comment by cgzones** [comment]
i still get the same warning (different line number) with the latest git.

my steps:

```
git clone https://github.com/westes/flex
cd flex/
./autogen.sh
./configure
make
cd ../

git clone https://github.com/SELinuxProject/selinux
cd selinux/
make DESTDIR=$(pwd)/build install
```

result:
```
cc -Werror -Wall -W -Wundef -Wshadow -Wmissing-format-attribute -O2 -I. -I../include -D_GNU_SOURCE -I../cil/include -fPIC -c -o ../cil/src/cil_lexer.o ../cil/src/cil_lexer.c
<stdout>: In function ‘yy_get_next_buffer’:
<stdout>:1113:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

**Comment by westes** [comment]
What flex are you using in the build of selinux?

On Friday, 26 February 2016, 10:25 am -0800, cgzones <notifications@github.com> wrote:

> i still get the same warning (different line number) with the latest git.
> 
> my steps:
> 
> ```
> git clone https://github.com/westes/flex
> cd flex/
> ./autogen.sh
> ./configure
> make
> cd ../
> 
> git clone https://github.com/SELinuxProject/selinux
> cd selinux/
> make DESTDIR=$(pwd)/build install
> ```
> 
> result:
> ```
> cc -Werror -Wall -W -Wundef -Wshadow -Wmissing-format-attribute -O2 -I. -I../include -D_GNU_SOURCE -I../cil/include -fPIC -c -o ../cil/src/cil_lexer.o ../cil/src/cil_lexer.c
> <stdout>: In function ‘yy_get_next_buffer’:
> <stdout>:1113:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/61#issuecomment-189412500

-- 
Will Estes
westes575@gmail.com

**Comment by cgzones** [comment]
i still get the same warning (different line number) with the latest git.

my steps:

```
git clone https://github.com/westes/flex
cd flex/
./autogen.sh
./configure
make
cd ../

git clone https://github.com/SELinuxProject/selinux
source='LEX = flex'
replace='LEX = ..\/..\/..\/flex\/src\/flex'
sed -i "s/${source}/${replace}/g" selinux/libsepol/src/Makefile
cd selinux/
make DESTDIR=$(pwd)/build install
```

result:
```
../../../flex/src/flex -t ../cil/src/cil_lexer.l > ../cil/src/cil_lexer.c
cc -Werror -Wall -W -Wundef -Wshadow -Wmissing-format-attribute -O2 -I. -I../include -D_GNU_SOURCE -I../cil/include -fPIC -c -o ../cil/src/cil_lexer.o ../cil/src/cil_lexer.c
<stdout>: In function ‘yy_get_next_buffer’:
<stdout>:1098:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

**Comment by westes** [comment]
Thanks for the clarification. You should now see this compile. I get no output from the compilation command with the change I just committed and pushed.

**Comment by cgzones** [comment]
Thanks, it works now

**Comment by grahamc** [comment]
Hi @westes, can you provide a patch NixOS could apply to 2.6.1 to resolve this? We tried applying https://github.com/westes/flex/commit/3946924ed5e77420c453bf841603c7278766093abut it doesn't apply cleanly. We're finding we'll need to patch several packages with `-Wno-error=sign-compare` but would prefer applying a patch to flex itself. 

/cc https://github.com/NixOS/nixpkgs/pull/19129

**Comment by vcunat** [comment]
BTW, it's not just NixOS. I believe e.g. Debian (still) suffers from this as well on 2.6.1: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835542#59

**Comment by RalphCorderoy** [comment]
Regarding the 2.6.1 problem, I've opened #97.

**Comment by ChristophBerg** [comment]
I'll be pushing https://github.com/oftc/flex/commit/8d18a80c8e8e94de0b172615e461270bdb360a6d to Debian to fix this in 2.6.1.

**Comment by vcunat** [comment]
I just wonder, why not 2.6.3 directly?

**Comment by westes** [comment]
Because Debian likes to keep old obsolete versions around. That patch doesn't apply against 2.6.3 anyways.

On Friday, 30 December 2016,  3:42 pm -0800, Vladimír Čunát <notifications@github.com> wrote:

> I just wonder, why not 2.6.3 directly?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/61#issuecomment-269835547

-- 
Will Estes
westes575@gmail.com
